=== swanwish/swhelper/schema/db.dtd
<?xml version="1.0"?>
        <!ELEMENT db (table|view|abstracttable|include)*>
        <!ATTLIST db
                description CDATA #IMPLIED
                name CDATA #REQUIRED>
        <!ELEMENT table (column)*>
        <!ATTLIST table
                description CDATA #IMPLIED
                name CDATA #REQUIRED>
        <!ELEMENT column (#PCDATA)>
        <!ATTLIST column
                autoincrement CDATA #IMPLIED
                description CDATA #IMPLIED
                json CDATA #IMPLIED
                xml CDATA #IMPLIED
                length CDATA #IMPLIED
                name CDATA #REQUIRED
                notnull CDATA #IMPLIED
                pk CDATA #IMPLIED
                skipupdate CDATA #IMPLIED
                type (SMALLINT|INT|BIGINT|VARCHAR|TEXT|NUMERIC|LONGTEXT|DECIMAL) #REQUIRED
                unique CDATA #IMPLIED
                default CDATA #IMPLIED>
        <!ELEMENT view (sql)*>
        <!ATTLIST view
                name CDATA #REQUIRED
                description CDATA #IMPLIED>
        <!ELEMENT sql (#PCDATA)>
        <!ELEMENT abstracttable (column)*>
        <!ATTLIST abstracttable
                id CDATA #IMPLIED
                description CDATA #IMPLIED>
        <!ELEMENT include EMPTY>
        <!ATTLIST include
                file CDATA #REQUIRED>

=== swanwish/swhelper/schema/sw_resource.xml
<?xml version="1.0"?>
<!DOCTYPE db SYSTEM "db.dtd">
<db name="sw_resource">
    <table name="t_request_data">
        <column name="request_id" type="BIGINT" pk="1" autoincrement="1" json="requestId"/>
        <column name="request_url" type="VARCHAR" length="512" notnull="1" json="requestUrl"/>
        <column name="query_param" type="VARCHAR" length="1024" notnull="1" json="queryParam"/>
        <column name="status" type="INT" notnull="1" json="status"/>
        <column name="url_content" type="LONGTEXT" notnull="1" json="urlContent"/>
        <column name="create_time" type="INT" notnull="1" skipupdate="1" json="createTime"/>
    </table>
</db>
